### ISSUE TITLE
SVG: saving

### ISSUE THREAD

**Issue by T4rikA** [T4rikA/lively.next#65]
We have to change the way the saving works, now we just store the url, but the svg on disk is not changed when saving. So when loading the world, the original svg from the disk is loaded. 
Instead I think we should save the actual path with the changes.

**Comment by Paula-Kli** [comment]
I rebased svg-halo to the current version of main of today and saved an SVG. While we are not fetching the SVG from the url anymore anyways I can find the `SVGPathString` in the saved json and also are able to reload the saved world.
Thus, I am closing the issue for now
