### ISSUE TITLE
First draft for intermediate presentation

### ISSUE THREAD

**Issue by LucPrestin** [T4rikA/lively.next#7]
- hack together some slides for the presentation
- content ideas:
   - problem (by an example)
   - our approach in theory
   - what we did so far (demo)
   - what we want to achieve until the seminar ends

**Comment by T4rikA** [comment]
https://docs.google.com/presentation/d/11918myNFL4G24_IHUT_A36kMugSnJC9kpvkjRtsSvnE/edit?usp=sharing
